### ISSUE TITLE
API Call

### ISSUE THREAD

**Issue by andreaschandra** [jakartaresearch/JREO#8]
How to declare class L8Biome

**Comment by rubentea16** [comment]
> @juannat95 btw yang L8Biome bisa dipanggil kek gini aja kah
> 
> ```python
> import jreo
> 
> source = jreo.L8Biome()
> source.download(n=2, out_dir='./', land_category=['forest'], cloud_status=['clear'], shadows=False) 
> ```


@andreaschandra  Bisa cuman di file __init__.py perlu tambahin ini
![image](https://user-images.githubusercontent.com/46805454/115584833-4bf58180-a2f5-11eb-80d3-389485dc3cb0.png)

cuman nnti folder downloadnya berubah dari `dataset/L8Biome' jadi 'L8Biome'
